import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * Export a study plan as a styled PDF document
 * @param {Array} plan - Array of day objects
 * @param {Object} metadata - { difficulty, hoursPerDay, daysAvailable, examDate }
 */
export const exportPlanAsPDF = (plan, metadata = {}) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(99, 102, 241);
  doc.rect(0, 0, pageWidth, 35, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('Syllabus2Success', 14, 18);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('AI-Powered Study Plan', 14, 26);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth - 14, 18, { align: 'right' });

  // Meta info
  doc.setTextColor(50, 50, 50);
  doc.setFontSize(11);
  let y = 45;
  const meta = [
    `Difficulty: ${(metadata.difficulty || 'medium').toUpperCase()}`,
    `Hours/Day: ${metadata.hoursPerDay || '-'}`,
    `Days Available: ${metadata.daysAvailable || plan.length}`,
    `Exam Date: ${metadata.examDate || '-'}`,
  ];
  doc.text(meta.join('   |   '), 14, y);
  y += 10;

  // Table
  const tableData = plan.map((day) => [
    `Day ${day.day}`,
    day.revision ? '🔄 Revision' : '📖 Study',
    (day.topics || []).join(', '),
    day.duration || '-',
    day.completed ? '✅' : '⬜',
  ]);

  autoTable(doc, {
    startY: y,
    head: [['Day', 'Type', 'Topics', 'Duration', 'Status']],
    body: tableData,
    headStyles: {
      fillColor: [99, 102, 241],
      textColor: 255,
      fontStyle: 'bold',
      fontSize: 9,
    },
    bodyStyles: { fontSize: 8, textColor: [30, 30, 30] },
    alternateRowStyles: { fillColor: [245, 247, 255] },
    columnStyles: {
      0: { cellWidth: 18 },
      1: { cellWidth: 24 },
      2: { cellWidth: 95 },
      3: { cellWidth: 22 },
      4: { cellWidth: 16 },
    },
    margin: { left: 14, right: 14 },
    styles: { overflow: 'linebreak', cellPadding: 3 },
  });

  // Footer
  const finalY = doc.lastAutoTable.finalY + 15;
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Generated by Syllabus2Success — https://github.com/Maganti-Praveen/gen-ai', 14, finalY);

  doc.save('study-plan.pdf');
};
